title: Create REST server with NodeJS and Express
tagline: Learn the basics to create an Express server and follow the REST principles.
description: Learn the basics to create an Express server and follow the REST principles.
